<?php

/**
 * @file
 * Code for Tieto_wysiwyg module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\tieto_wysiwyg\Plugin\CKEditorPlugin\VideoPopupPlugin;
use Drupal\tieto_wysiwyg\Plugin\CKEditorPlugin\ImagePopupPlugin;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function tieto_wysiwyg_form_node_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id
) {
  $form['#attached']['library'][] = 'tieto_wysiwyg/ckeditor_modifications';
}

/**
 * Implements hook_ckeditor_plugin_info_alter().
 */
function tieto_wysiwyg_ckeditor_plugin_info_alter(array &$plugins) {
  $plugins['tieto_image'] = [
    'id' => 'tieto_image',
    'label' => \t('Tieto specific plugins'),
    'module' => 'tieto_wysiwyg',
    'class' => ImagePopupPlugin::class,
    'provider' => 'tieto_wysiwyg',
  ];
  $plugins['tieto_video'] = [
    'id' => 'tieto_video',
    'label' => \t('Tieto specific plugins'),
    'module' => 'tieto_wysiwyg',
    'class' => VideoPopupPlugin::class,
    'provider' => 'tieto_wysiwyg',
  ];
}

/**
 * Implements hook_ckeditor_css_alter().
 */
function tieto_wysiwyg_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = \drupal_get_path('module', 'tieto_wysiwyg') . '/css/wysiwyg_style.css';
}

/**
 * Implements hook_page_attachments().
 */
function tieto_wysiwyg_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'tieto_wysiwyg/ckeditor_image_video';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function tieto_wysiwyg_preprocess_page(&$variables) {
  /* @var \Drupal\node\Entity\Node $node */
  $node = $variables['node'] ?? NULL;

  if (\is_object($node) && $node->hasField('field_side_block')) {
    $side_block = $node->get('field_side_block');
    if ($side_block !== NULL && $side_block->count() > 0) {
      $variables['#attached']['library'][] = 'tieto_wysiwyg/double_image';
    }
  }
}
