<?php

/**
 * @file
 * Tieto Link Customization module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\tieto_link_customization\Permission\LinkPermissions;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Customize features from "Editor Advanced Link".
 *
 * @see: editor_advanced_link_form_editor_link_dialog_alter
 */
function tieto_link_customization_form_editor_link_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  $currentUser = \Drupal::currentUser();

  foreach (LinkPermissions::ATTRIBUTES as $attribute) {
    if (!isset($form['attributes'][$attribute])) {
      continue;
    }

    $form['attributes'][$attribute]['#access'] = $form['attributes'][$attribute]['#access']
      && (
        $currentUser->hasPermission('edit all link attributes')
        || $currentUser->hasPermission("edit $attribute link attribute")
      );
  }
}
